# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hht/Downloads/Qtaichi-master/src/App/Qtaichi/minidraw.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Minidraw(object):

    def setupUi(self, Minidraw):
        Minidraw.setObjectName("Minidraw")
        Minidraw.resize(1200, 1000)
        self.menuBar = QtWidgets.QMenuBar(Minidraw)
        self.menuBar.setObjectName("menuBar")
        Minidraw.setMenuBar(self.menuBar)
        self.centralWidget = QtWidgets.QWidget(Minidraw)
        self.centralWidget.setObjectName("centralWidget")
        Minidraw.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(Minidraw)
        self.statusBar.setObjectName("statusBar")
        Minidraw.setStatusBar(self.statusBar)

        self.retranslateUi(Minidraw)
        QtCore.QMetaObject.connectSlotsByName(Minidraw)

    def retranslateUi(self, Minidraw):
        _translate = QtCore.QCoreApplication.translate
        Minidraw.setWindowTitle(_translate("Minidraw", "Minidraw"))
